Dec 26 09:12:05 raspberrypi systemd[1]: Started runAGC.service - Run AGC Script.
Dec 26 09:12:05 raspberrypi runAGC.sh[5750]: Starting VirtualAGC
Dec 26 09:12:05 raspberrypi runAGC.sh[5750]: Starting DSKY
Dec 26 09:12:05 raspberrypi sudo[5753]: gazzapac-dsky : PWD=/home/gazzapac-dsky ; USER=root ; COMMAND=/usr/bin/python3 piDSKY-gp.py
Dec 26 09:12:05 raspberrypi sudo[5753]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]: Display will be dimmned
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]: Display will be tested
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]: Display will be cleared
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]: Traceback (most recent call last):
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]:   File "/home/gazzapac-dsky/piDSKY-gp.py", line 458, in <module>
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]:     echoOn(False)
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]:   File "/home/gazzapac-dsky/piDSKY-gp.py", line 450, in echoOn
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]:     new = termios.tcgetattr(fd)
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]:           ^^^^^^^^^^^^^^^^^^^^^
Dec 26 09:12:09 raspberrypi runAGC.sh[5755]: termios.error: (25, 'Inappropriate ioctl for device')
Dec 26 09:12:10 raspberrypi sudo[5753]: pam_unix(sudo:session): session closed for user root
Dec 26 09:12:10 raspberrypi systemd[1]: runAGC.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 09:12:10 raspberrypi systemd[1]: runAGC.service: Failed with result 'exit-code'.
Dec 26 09:12:10 raspberrypi systemd[1]: runAGC.service: Scheduled restart job, restart counter is at 123.
Dec 26 09:12:10 raspberrypi systemd[1]: Stopped runAGC.service - Run AGC Script.
